name: CI/CD Pipeline for Snowflake with Colab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours (e.g., 00:00, 03:00, 06:00 UTC)

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install snowflake-connector-python pandas flake8

      - name: Lint with Flake8
        run: |
          flake8 process_data.py --max-line-length=300

      - name: Syntax Check
        run: python -m py_compile process_data.py

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install snowflake-connector-python pandas

      - name: Set Environment Variables
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          echo "SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD" >> $GITHUB_ENV

      - name: Run Processing Script
        run: |
          python process_data.py
        env:
          SNOWFLAKE_PASSWORD: ${{ env.SNOWFLAKE_PASSWORD }}

      - name: Log Completion
        if: success()
        run: echo "Data processing completed and written to Snowflake"
